In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'

In [3]:
!wget $data -O course_lead_scoring.csv

--2026-01-03 22:12:04--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.001s

2026-01-03 22:12:04 (51.6 MB/s) - ‘course_lead_scoring.csv’ saved [80876/80876]

In [4]:
df = pd.read_csv('course_lead_scoring.csv')

In [5]:
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [6]:
categorical_columns = list(df.dtypes[df.dtypes=='object'].index) #alexey, requires logic and understadning masks hehe


for c in categorical_columns:
    df[c] = df[c].fillna('NA')

In [12]:
numerical_columns = list(df.dtypes[df.dtypes!='object'].index) 
#assumed anything that is not object is a number, this might be a bad idea though.


for c in numerical_columns:
    df[c] = df[c].fillna(0.0)

In [13]:
numerical_columns

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [15]:
df[numerical_columns].isna().sum()

number_of_courses_viewed    0
annual_income               0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [17]:
df[categorical_columns].isna().sum()
# confirmed.

lead_source          0
industry             0
employment_status    0
location             0
dtype: int64

In [18]:
df.industry.mode()

0    retail
Name: industry, dtype: object

In [29]:
df[numerical_columns].corr()

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879,0.435914
annual_income,0.009770,1.000000,0.027036,0.015610,0.053131
interaction_count,-0.023565,0.027036,1.000000,0.009888,0.374573
lead_score,-0.004879,0.015610,0.009888,1.000000,0.193673
converted,0.435914,0.053131,0.374573,0.193673,1.000000

In [32]:
df.interaction_count.corr(df.lead_score)

np.float64(0.009888182496913084)

In [33]:
df.number_of_courses_viewed.corr(df.lead_score)

np.float64(-0.004878998354681257)

In [34]:
df.number_of_courses_viewed.corr(df.interaction_count)

np.float64(-0.023565222882888117)

In [35]:
df.annual_income.corr(df.interaction_count)

np.float64(0.02703647240481436)